#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

# Author: ktodisco

case "$1" in
	start)
		echo "Starting ambilight service."
		/usr/bin/ambilight
		;;
	stop)
		echo "Stopping ambilight service."
		killall ambilight
		;;
	*)
		echo "Usage: /etc/init.d/ambilight [start|stop]"
		exit 1
		;;
esac

exit 0
